spring.application.name=OAuth-ResourceService
server.port=7070
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://127.0.0.1:9090
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://127.0.0.1:9090/oauth2/jwks
