spring.application.name=AuthorizationServer
server.port=9090
logging.level.org.springframework.security=trace
spring.security.oauth2.authorizationserver.client.FMS.registration.client-id=client
spring.security.oauth2.authorizationserver.client.FMS.registration.client-secret=secret
spring.security.oauth2.authorizationserver.client.FMS.registration.client-name=FMS
spring.security.oauth2.authorizationserver.client.FMS.registration.client-authentication-methods=client_secret_basic
spring.security.oauth2.authorizationserver.client.FMS.registration.authorization-grant-types=authorization_code
spring.security.oauth2.authorizationserver.client.FMS.registration.redirect-uris=http://localhost:8080/login/oauth2/code/fms
spring.security.oauth2.authorizationserver.client.FMS.registration.scopes=openid
spring.security.oauth2.authorizationserver.client.FMS.jwk-set-uri=http://127.0.0.1:9090/oauth2/jwks