spring.application.name=Cli[FMS]
#DataBaseProperties
	spring.datasource.url=jdbc:mysql://localhost/musicservicedb
	spring.datasource.username = codeman
	spring.datasource.password = codeman.MySQL.getPassword();
	spring.sql.init.mode=always
	#spring.jpa.hibernate.ddl-auto=create-drop
	#spring.jpa.hibernate.ddl-auto=validate
	spring.jpa.hibernate.ddl-auto=update
#	spring.jpa.show-sql=true
	spring.jpa.database=mysql
#OAuth2ClientProperties
	#FMS-Authentication:
#		FMS-Provider
		spring.security.oauth2.client.provider.fms_provider.issuer-uri=http://127.0.0.1:9090
	#FMS-Authentication
		spring.security.oauth2.client.registration.FMS.client-id=client
		spring.security.oauth2.client.registration.FMS.client-secret=secret
		spring.security.oauth2.client.registration.FMS.client-name=Authentication	
		spring.security.oauth2.client.registration.FMS.authorization-grant-type=authorization_code
		spring.security.oauth2.client.registration.FMS.client-authentication-method=client_secret_basic
		spring.security.oauth2.client.registration.FMS.provider=fms_provider
		spring.security.oauth2.client.registration.FMS.redirect-uri=http://localhost:8080/login/oauth2/code/FMS
		spring.security.oauth2.client.registration.FMS.scope=openid

	#YandexAuthentication:
		#Yandex-Provider
		spring.security.oauth2.client.provider.yandex.token-uri=https://oauth.yandex.ru/token
		spring.security.oauth2.client.provider.yandex.authorization-uri=https://oauth.yandex.ru/authorize
		spring.security.oauth2.client.provider.yandex.user-info-uri=https://login.yandex.ru/info
		spring.security.oauth2.client.provider.yandex.user-name-attribute=default_email
	#Yandex-Authentication
		spring.security.oauth2.client.registration.yandex.client-id=8d0509523fee449ab755605489ff3c24
		spring.security.oauth2.client.registration.yandex.client-secret=a3f6f397401a4ddfa17229a5a9be5eb2
		spring.security.oauth2.client.registration.yandex.client-name=Yandex
		spring.security.oauth2.client.registration.yandex.provider=yandex
		spring.security.oauth2.client.registration.yandex.authorization-grant-type=authorization_code
		spring.security.oauth2.client.registration.yandex.client-authentication-method=client_secret_basic
		spring.security.oauth2.client.registration.yandex.redirect-uri=http://localhost:8080/login/oauth2/code/yandex